version: '2'

services:
    app:
        image: $NW_REGISTRY/${COMPOSE_PROJECT_NAME}_app:${NW_VERSION_TAG}
        build:
            context: .
            dockerfile: ./docker/app/Dockerfile
        environment:
            NW_MODE: $NW_MODE
            NW_ENV: $NW_ENV
            NW_WAIT_FOR_HOSTS: "selenium_hub:4444 chrome:5900 firefox:5900"
            NW_WAIT_FOR_TIMEOUT: 10
            NW_HOST_UID: $NW_HOST_UID
            NW_HOST_GID: $NW_HOST_GID
        depends_on:
            - selenium_hub
        command: $NW_APP_COMMAND

    selenium_hub:
        image: selenium/hub:3.0.1-aluminum
        environment:
            GRID_TIMEOUT: $NW_SELENIUM_GRID_TIMEOUT
            GRID_BROWSER_TIMEOUT: $NW_SELENIUM_GRID_BROWSER_TIMEOUT

    chrome:
        image: selenium/node-chrome-debug:3.0.1-aluminum
        depends_on:
            - selenium_hub
        volumes:
            - /dev/shm:/dev/shm
        environment:
            HUB_PORT_4444_TCP_PORT: 4444
            HUB_PORT_4444_TCP_ADDR: selenium_hub
            TZ: $NW_SELENIUM_TIME_ZONE
            no_proxy: $NW_SELENIUM_NO_PROXY

    firefox:
        image: selenium/node-firefox-debug:3.0.1-aluminum
        depends_on:
            - selenium_hub
        environment:
            HUB_PORT_4444_TCP_ADDR: selenium_hub
            HUB_PORT_4444_TCP_PORT: 4444
            TZ: $NW_SELENIUM_TIME_ZONE
            no_proxy: $NW_SELENIUM_NO_PROXY

volumes:
    app:
        driver: local
