version: '2'

services:
    app:
        restart: always
        volumes:
            - app:/app

    selenium_hub:
        restart: always

    chrome:
        restart: always

    firefox:
        restart: always
