version: '2'

services:
    app:
        build:
            context: .
            dockerfile: ./docker/app/Dockerfile
        tty: true
        environment:
            NW_WAIT_FOR_HOSTS: "selenium_hub:4444 chrome:5900 firefox:5900"
            NW_WAIT_FOR_TIMEOUT: 10
            NW_HOST_UID: $NW_HOST_UID
            NW_HOST_GID: $NW_HOST_GID
            NW_CONTAINER_USER: $NW_CONTAINER_USER
            NW_CONTAINER_GROUP: $NW_CONTAINER_GROUP
        volumes:
            - $NW_APP_VOLUME_PATH:/nightwatch
        depends_on:
            - selenium_hub

    selenium_hub:
        image: selenium/hub:3.0.1-aluminum
        environment:
            GRID_TIMEOUT: $NW_SELENIUM_GRID_TIMEOUT
            GRID_BROWSER_TIMEOUT: $NW_SELENIUM_GRID_BROWSER_TIMEOUT

    chrome:
        image: selenium/node-chrome-debug:3.0.1-aluminum
        depends_on:
            - selenium_hub
        ports:
            - $NW_CHROME_VNC_PORT:5900
        environment:
            HUB_PORT_4444_TCP_PORT: 4444
            HUB_PORT_4444_TCP_ADDR: selenium_hub
            TZ: $NW_SELENIUM_TIME_ZONE
            no_proxy: $NW_SELENIUM_NO_PROXY

    firefox:
        image: selenium/node-firefox-debug:3.0.1-aluminum
        depends_on:
            - selenium_hub
        ports:
            - $NW_FIREFOX_VNC_PORT:5900
        environment:
            HUB_PORT_4444_TCP_ADDR: selenium_hub
            HUB_PORT_4444_TCP_PORT: 4444
            TZ: $NW_SELENIUM_TIME_ZONE
            no_proxy: $NW_SELENIUM_NO_PROXY
